# Generated by Django 4.2 on 2023-05-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='submit_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=255)),
                ('mob', models.IntegerField(max_length=10)),
            ],
        ),
    ]
